name: run main.py

# on: [push]
on: workflow_dispatch
  # schedule:
  #   - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          GROQ_API_BASE: ${{ secrets.GROQ_API_BASE }}
          GROQ_MODEL_NAME: ${{ secrets.GROQ_MODEL_NAME }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          XUSERNAME: ${{ secrets.XUSERNAME }}
          XEMAIL: ${{ secrets.XEMAIL }}
          XPASSWORD: ${{ secrets.XPASSWORD }}
          AUTOGEN_USE_DOCKER: ${{ secrets.AUTOGEN_USE_DOCKER }}
        run: python main.py

      - name: commit files
        run: |
          git config --local user.email "nikhilreddy.maligireddy1@gmail.com"
          git config --local user.name "notnikhilreddy"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated url logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.AI_INFORMER_PUSH_TOKEN }}
          branch: main 