name: run main.py

# on: [push]
on: workflow_dispatch
  # schedule:
  #   - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          GROQ_API_BASE: ${{ secrets.GROQ_API_BASE }}
          GROQ_MODEL_NAME: ${{ secrets.GROQ_MODEL_NAME }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          XUSERNAME: ${{ secrets.XUSERNAME }}
          XEMAIL: ${{ secrets.XEMAIL }}
          XPASSWORD: ${{ secrets.XPASSWORD }}
          XUSERNAME_TEST: ${{ secrets.XUSERNAME_TEST }}
          XEMAIL_TEST: ${{ secrets.XEMAIL_TEST }}
          XPASSWORD_TEST: ${{ secrets.XPASSWORD_TEST }}
          RELEASE: ${{ secrets.RELEASE }}
        run: python main.py

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.AI_INFORMER_PUSH_TOKEN }}
        run: |
          git config --global user.name "notnikhilreddy"
          git config --global user.email "nikhilreddy.maligireddy1@gmail.com"
          git add .
          git commit -m "automated workflow commit"
          git push --force